before_install:
  - chmod +x gradlew

language: java
jdk:
  -openjdk11

before_deploy:
  - rvm requirements
  - rvm install 2.6
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-storeapp-demo"